name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install Conan
      id: conan
      uses: turtlebrowser/get-conan@main

    - name: Conan version
      run: echo "${{ steps.conan.outputs.version }}"

    - name: Checkout repository
      uses:  stepniakadam/CPPStaticBooster@v1
      
    - name: List all files
      uses:  ls -al
      
      
      
