name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:    
    - uses: actions/checkout@v2
          
    - name: Checkout repository
      uses: stepniakadam/CPPStaticBooster@main
      
    - name: Install Conan
      id: conan
      uses: turtlebrowser/get-conan@main

    - name: Conan version
      run: echo "${{ steps.conan.outputs.version }}"
      
    - name: List all files
      run:  ls -al
      
      
